driver:
  name: vagrant

#provisioner:
#  name: puppet_apply
#  # Not installing chef since inspec is used for testing
#  require_chef_for_busser: false
#  manifests_path: <%= ENV[('PWD')] %>/spec/fixtures/manifests
#  modules_path: <%= ENV[('PWD')] %>/spec/fixtures/modules

verifier:
  name: inspec
  sudo: false

platforms:
  - name: centos-7
    driver:
      box: centos/7

suites:
  - name: default
    verifier:
      inspec_tests:
        # if you want to use your local code
        - file://<%= ENV[('PWD')] %>/profiles/disa_stig-rhel7-baseline
        # if you want to use the current profile in the git repo
        #- git: https://github.com/<...>-baseline.git
     #controls:
     #  - V-72895
     #attrs:
     #  - attributes.yml
